#' Get objects from the RATO ArcGIS Enterprise environment via the API
#'
#' @param object_ids Vector of object_ids, will be converted to character.
#' @param token Access token, by default generated by `get_token()`
#'
#' @return tibble of requested objects.
#' @export
get_objects <- function(object_ids,
                        token = get_token(),
                        domain = "https://gis.oost-vlaanderen.be/server/rest/services/",
                        table_path = c("RATO2",
                                       "RATO2_Dossiers_Publiek",
                                       "MapServer")) {
  # Assert that objects were requested
  assertthat::assert_that(assertthat::not_empty(object_ids))

  # Collate the object id's to query and format them as expected for the API
  object_id_query <- glue::glue(
    "OBJECTID IN ({object_ids_collated})",
    object_ids_collated = glue::glue_collapse(object_ids,
                                              sep = ","
    )
  ) %>%
    curl::curl_escape()

  # Build request for the API
  objects_request <-
    httr2::request(domain) %>%
    httr2::req_url_path_append(table_path,
                               "0",
                               glue::glue("query?where={object_id_query}")) %>%
    httr2::req_url_query(
      outFields = "*",
      f = "json",
      token = token
    )

  # Parse the response
  objects_response <-
    objects_request %>%
    httr2::req_perform() %>%
    httr2::resp_body_json()

  # Foreward any error messages
  assertthat::assert_that(
    isTRUE(purrr::pluck(objects_response, "error", "message", .default = TRUE)),
    msg = purrr::pluck(objects_response, "error", "message")
  )

  # Pluck (so an error is returned if missing) the parts of the response we
  # want, and convert it into tabular form, then return it.

  objects_response %>%
    purrr::chuck("features") %>%
    purrr::map(~ purrr::pluck(.x, "attributes")) %>%
    purrr::map_dfr(~.x) %>%
    return()
}
