#' List all object ids in the RATO ArcGIS Enterprise MapServer
#'
#' @param token Access token, by default generated by `get_token()`
#' @param domain URL to the ArcGIS Server GIS services
#' @param table_path Vector of strings, the path to the table in the MapServer
#' @param query Vector of strings, the query to the table in the MapServer
#'
#' @return Integer vector of (all) object ids.
#' @export
list_object_ids <- function(token = get_token(),
                            domain = "https://gis.oost-vlaanderen.be/server/rest/services/",
                            table_path = c("RATO2",
                                            "RATO2_Dossiers_Publiek",
                                            "MapServer"),
                            query = c("0", "query?where=1%3D1")) {

  object_ids_response <-
    httr2::request(domain) %>%
    httr2::req_url_path_append(table_path,query) %>%
    httr2::req_url_query(
      returnIdsOnly = "true",
      f = "pjson",
      token = token
    ) %>%
    httr2::req_perform() %>%
    httr2::resp_body_json(check_type = FALSE)

  object_ids_response %>%
    purrr::chuck("objectIds") %>%
    unlist() %>%
    return()
}
